### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by sterlu** [MATF-RG17/RG145-simulator-voznje#1]

**Comment by sterlu** [comment]
Kolega je prijavio da na njegovom računaru sa Linux distribucijom igra ne radi dobro (auto se zabije u zid odmah). Jedno predloženo rešenje je smanjivanje MAX_FORWARD i MAX_REVERSE konstanti za nekoliko redova veličina. 

Trenutno nisam siguran zašto se prijavljeno ponašanje dešava. Priložio sam video snimak ekrana sa mog računara koji prikazuje očekivano ponašanje. 

Radim na otklanjanju problema i cenio bih bilo kakve smernice. Takođe bi mi značilo da znam kakvo ponašanje se dešava na Vašem računaru.

**Comment by ivan-cukic-matf** [comment]
I kod mene se "zabije u zid odmah".

Ne vidim da koristite bilo šta što bi trebalo da zavisi od platforme. Probajte da dodate printf-ove da biste videli kako se menjaju promenljive vezane za brzinu automobila.
